name: Build and test React App

on:
    push:
        branches: ['main']

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21
                  cache: 'npm'

            - run: npm ci
            - run: npm run build
            
            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: 'dist'

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
